### PR TITLE
fix(charts): Handle asynchrone inputs and color updates

### PR DESCRIPTION
**Pull request by adrienboulle**
fix asynchronous data binding and color update

probably related to #666 #619 and #424

### CODE REVIEW

**Comment by vilbara** [comment]
Tested with cherry-pick on "1.5.0" tag: The fix works in general, however update animation is broken even when the length of dataSets is not changed: Charts gets re-rendered instead of adjusted, e.g. visible on bar-charts - they grow from "0" instead of adjusting existing values.

Chart also gets reset to the standard 300x150px size so I need to call "this.chartDirective.chart.resize()" after new dataSets. (I do not use responsive sizing but calling the aforementioned resize() manually due to performance reasons).

**Comment by jimmykane** [comment]
Cna this be finally merged?

**Comment by jimmykane** [comment]
@valorkin Please lets move on with this.

**Comment by jimmykane** [comment]
As a workarround for this 

`@ViewChild(BaseChartDirective) childCmpBaseChartRef: any;` to get the BaseChart 

and then later onChange probably

```
if (this.childCmpBaseChartRef.chart && this.childCmpBaseChartRef.chart.config && this.childCmpBaseChartRef.chart.config.data && this.childCmpBaseChartRef.chart.config.data.datasets.length > this.lineChartData.length) {
      this.childCmpBaseChartRef.chart.update();
    }
```

**Comment by jimmykane** [comment]
Sorry for the deteleted comment but here is my workarround: 

```
if (this.childCmpRef.chart && this.childCmpRef.chart.config && this.childCmpRef.chart.config.data && this.childCmpRef.chart.config.data.datasets.length > this.lineChartData.length) {
      this.childCmpRef.chart.config.data.datasets.forEach((dataset, index) => {
        if (!this.lineChartData.find((lineChartData) => {
            return lineChartData.label === dataset.label;
          })) {
          this.childCmpRef.chart.config.data.datasets.splice(1, index);
        }
      });
      this.childCmpRef.chart.update();
    }
```

**Comment by jimmykane** [comment]
Ok my workarround that works is: 

```
  @ViewChild(BaseChartDirective) childCmpBaseChartRef: any;
```

To get the directive and then on `ngOnInit()` , when the data with new dimensions come in: 
```
if (this.childCmpBaseChartRef.datasets && this.childCmpBaseChartRef.datasets.length !== this.lineChartData.length) {
      this.childCmpBaseChartRef.datasets = this.lineChartData;
      this.childCmpBaseChartRef.ngOnInit();
    }
```

Ugly but actually https://github.com/valor-software/ng2-charts/pull/736 solves this correct

**Pull request closed without merging**
