### PR TITLE
Refresh Chart on Options Change

### PR DESCRIPTION
**Pull request by BradyLiles**

### CODE REVIEW

**Comment by BradyLiles** [comment]
Finally got all the linter issues!!! (:

**Comment by BradyLiles** [comment]
By the way Valor... I'm going to be doing A LOT of work with ng2-charts here and I have no issue helping maintain this Repo and working on some of these outstanding issues if you ever need any help.
Let me know! (:

**Comment by valorkin** [comment]
@BradyLiles sounds good to me,
please join slack https://ng2-team.herokuapp.com/

**Comment by valorkin** [comment]
please rebase on top of development and squash it ;)
because it is hard to review

**Comment by BradyLiles** [comment]
Awesome, thanks Valor. 
I believe you sent me the wrong link for your slack team though.

**Comment by valorkin** [comment]
hey, thanks for your time
just released v1.5.0
if your issue is still there please update PR

**Comment by ryan-morris** [comment]
@BradyLiles I assume this would fix #547? Before my labels and data would update, just not options. Now, with 1.5.0, labels do not appear to be updating for me either.

**Comment by objectizer** [comment]
are you guys still working on this ? i have an issue that when i change labels property it doesn't refresh the XAxis bar with the new labels.

**Comment by raugaral** [comment]
please merge this changes

**Comment by bop10** [comment]
when is this pull request going to be merged? thanks

**Pull request closed without merging**
