### PR TITLE
Fix the problem with adding\removing series

### PR DESCRIPTION
**Pull request by Neir0**
See https://github.com/valor-software/ng2-charts/issues/658

### CODE REVIEW

**Comment by dgpuranik** [comment]
What happened to this pull request? I am still having this issue at v1.6.0?

**Comment by dgpuranik** [comment]
@Neir0 I tried your code. I have attached the modified file here. Please let me know if I am missing something. 

I compiled the code with these changes in charts.ts. I put updated transpiled files in my app's ng-modules/ng2-charts. But, now, my all charts disappeared.
 
[charts-updated.txt](https://github.com/valor-software/ng2-charts/files/1074022/charts-updated.txt)

**Comment by jimmykane** [comment]
Any update on this ? @valorkin

**Comment by paviad** [comment]
I have taken the code from this repository and created a new package, made fresh with the latest Angular tools (Angular CLI 7.3.4 at the time of this posting). The package is called `ng2-charts7` and it may be found on github at https://github.com/paviad/ng2-charts7

It is also published on npmjs.com at https://www.npmjs.com/package/ng2-charts7

This issue is fixed in that package (it was the trigger that made me start the package in the first place)

**Pull request closed without merging**
