### PR TITLE
Angular 10 update (based on @santam85 pr #1240)

### PR DESCRIPTION
**Pull request by paviad**
Hey @santam85 I rebased your PR on `development` updated the financial chart and ran `npm run test:headless` there's an error with the financial chart, if you can fix it I would merge this PR.

Also should we bump the version to 2.4.0 or keep it at 2.3.*?

### CODE REVIEW

**Comment by paviad** [comment]
Continue at PR #1245

**Comment by santam85** [comment]
According to semver best practices, we should probably bump to 3.0.0 due to the update to a new Angular major...

**Comment by paviad** [comment]
Wouldn't it work with angular 7.2 - 10 ?

**Comment by santam85** [comment]
Good point, you are probably right, but I didn't test it.

**Comment by santam85** [comment]
Opened #1250 (the PR to rule them all), since I don't have push rights to your branch...

**Pull request closed without merging**
