### PR TITLE
Fixed Sizing issue on doughnut and pie charts

### PR DESCRIPTION
**Pull request by BradyLiles**
Fixed Sizing issue on doughnut and pie charts
https://plnkr.co/edit/MmddFU?p=preview

### CODE REVIEW

**Comment by valorkin** [comment]
nice and simple, thanks!

**Comment by BradyLiles** [comment]
Not a problem even though you removed my change in the next commit after the library went on the directive approach! haha xD

**Comment by valorkin** [comment]
Your commit pushed me to this :)

**Comment by naveedahmed1** [comment]
I think sizing issue still exists when using it with chartjs 2.5.0

**Pull request merged**
