### PR TITLE
fix(charts): Make charts dynamic and avoid re-rendering full chart on…

### PR DESCRIPTION
**Pull request by m0t0r**
… data change

@valorkin, can you please review this PR ? I've fixed the #215 and #379 and it's probably related to #198. The charts animate on data change without re-rendering. If everything is fine, please merge it and publish a new release, it's pretty important for us. Thanks

### CODE REVIEW

**Comment by m0t0r** [comment]
@valorkin, or anyone from @valor-software can you please review this PR ?

**Comment by valorkin** [comment]
Hey, sure. Oleg at the moment working on build proceed of this lib, so I can merge it asap

Huge thanks for your time and help !:)

**Comment by m0t0r** [comment]
Hi, yes, I would like this fix to be merged asap, my company's project depends on it. Thanks

Glad to help ;)

**Comment by valorkin** [comment]
@m0t0r I am merging https://github.com/valor-software/ng2-charts/pull/574 
an update to ng v2.3+ and merging your fix on top of it

**Comment by m0t0r** [comment]
@valorkin, thanks a lot 👍

**Comment by valorkin** [comment]
Demo redeployed with your changes in AoT mode, works much better now :)

**Pull request merged**
