### PR TITLE
v3.0.0 release

### PR DESCRIPTION
**Pull request by santam85**
Preparing the merge to master for v3.0.0 release

### CODE REVIEW

**Comment by damogallagher** [comment]
Hi

I was just wondering when this will be availble to use with Angular 13? Seeing some issues with the latest versions of chart.js and ng2-charts

**Comment by santam85** [comment]
@damogallagher Will have some time to complete it this weekend hopefully.

**Comment by damogallagher** [comment]
@santam85 I see v3.0.0 has been uploaded to npm
When I upgrade I get the following error - 
`
 - errorm TS2305: Module '"ng2-charts"' has no exported member 'Color'.

3 import { Label, Color } from 'ng2-charts';
`
Are Label and Color still included in the latest version of ng2-charts?
If not - is there any migration guide?

**Comment by santam85** [comment]
> @santam85 I see v3.0.0 has been uploaded to npm When I upgrade I get the following error -
> 
> ```
>  - errorm TS2305: Module '"ng2-charts"' has no exported member 'Color'.
> 
> 3 import { Label, Color } from 'ng2-charts';
> ```
> 
> Are Label and Color still included in the latest version of ng2-charts? If not - is there any migration guide?

No migration guide as of yet. I removed all types from ng2-charts and rely directly on the Chart.js ones. You can have a look at the examples in the docs (https://valor-software.com/ng2-charts/next/)

**Pull request merged**
