### PR TITLE
feat(angular): update to latest angular+ng-packagr libs to make compatible with Ivy project

### PR DESCRIPTION
**Pull request by leo6104**
Related issue: https://github.com/angular/angular/issues/32466

We can test this version with below command

```
npm i https://github.com/leo6104/ng2-charts.git#ng9-builds --save
```

### CODE REVIEW

**Comment by ciesielskico** [comment]
Can we get this going please?

**Comment by leo6104** [comment]
Update to latest official 9 version. Please consider it could be merged. Many ivy projects have an issue with ng2-charts.

**Comment by daniloff200** [comment]
@leo6104  I agree with these changes but, why you disabled Ivy?

**Comment by leo6104** [comment]
@daniloff200 https://angular.io/guide/ivy#maintaining-library-compatibility 

image

If we build library to Ivy compile version, it doesn't compatible with non-ivy projects.

**Comment by mfilar** [comment]
Hi, how it's going? Can we get this one soon..?

**Comment by alexis-landrieu-avanade** [comment]
Any news on this ?

**Comment by paviad** [comment]
Closed by ff54527b

**Pull request closed without merging**
