### PR TITLE
Register a plugin through the BaseChartDirective

### PR DESCRIPTION
**Pull request by bbreijer**
https://github.com/valor-software/ng2-charts/issues/496

### CODE REVIEW

**Comment by valorkin** [comment]
hey, thanks for a first PR
but question is: should we add a static method,
to globally accessible objects?

**Comment by bbreijer** [comment]
The main issue here is that you need access to the same `Chart` as the one used by the `BaseChartDirective `, therefore it makes sense to have the function in the `BaseChartDirective`.
Since the function is unrelated to objects of type `BaseChartDirective`, it makes sense to have it `static` in my opinion.

An example application which draws horizontal lines configured by the option `horizontalLines` is:

```
BaseChartDirective.registerPlugin({
      afterDraw: (chartInstance, easing) => {
        const xScale = chartInstance.scales['x-axis-0'];
        const ctx = chartInstance.chart.ctx;

        if (chartInstance.options.horizontalLines) {
          chartInstance.options.horizontalLines.map(({y, color}) => {
            // calculate the pixel using the scale
            const yPixel = chartInstance.scales['y-axis-0'].getPixelForValue(y);

            // draw line
            ctx.strokeStyle = color;
            ctx.beginPath();
            ctx.moveTo(Math.round(xScale.left), yPixel);
            ctx.lineTo(Math.round(xScale.right), yPixel);
            ctx.stroke();
          });
        }
      }
    });
```

**Comment by apellicc** [comment]
it's possible merge this pull request please

**Comment by rashmidixit** [comment]
Can we get this pull request merged please? There is a need to be able to put labels on top of stacked charts and I cannot do it without registering a plugin.

**Comment by apellicc** [comment]
Hello @rashmidixit, for register plugin is accessible in instance of your chart 
 " this.yourChart.chart.plugins.register() ".
For to access the instance Chart [https://github.com/valor-software/ng2-charts/issues/776](url)

**Comment by rashmidixit** [comment]
Hello @apellicc. Thank you for your quick response. However, this hasnt worked for me. I took the BaseChartDirective (variable chart) and tried to access the chart.plugin, however there is no such member variable. 
chart-issue

**Comment by apellicc** [comment]
sorry ^^ I forgot that I had modified ng2chart
[https://github.com/apellicc/Ng2-Charts-compiled/blob/master/charts/charts.js](url)

**Comment by brianeletype** [comment]
It would be great if we could merge this.  We'd really like to have access to the plugin system to get what we need out of one of our charts.

**Comment by anavgale** [comment]
What is the time frame for this pull request to get merged? Need to access the plugin system.
 
Thanks.

**Comment by tucq88** [comment]
Seems like all check is done, any worries that preventing this being merge ;) 
PS: No rush, just want to implement local plugins :D

**Comment by paviad** [comment]
I have taken the code from this repository and created a new package, made fresh with the latest Angular tools (Angular CLI 7.3.4 at the time of this posting). The package is called `ng2-charts7` and it may be found on github at https://github.com/paviad/ng2-charts7

It is also published on npmjs.com at https://www.npmjs.com/package/ng2-charts7

@bbreijer with your permission, I will take this pull request and integrate it into that package.

**Comment by bbreijer** [comment]
@paviad, thats fine by me. Thanks for the work on ng7.

**Comment by valorkin** [comment]
@pavid great work!
If you wish I could grant you access to this repo and npm if you would want to

**Comment by paviad** [comment]
I would, this is the most popular Angular library adapter for chart.js - and it needs serious work :)

**Comment by valorkin** [comment]
Write and merge access granted, npm publish granted.
You could join ngx-bootstrap slack and ping me there
If you will QAs help or anything
Right now we are almost finished with cypress coverage, adding bazel build, screenshot based testing, etc.

**Pull request closed without merging**
