### PR TITLE
Fix #1236 - Update peerDependencies to Angular 10

### LINKED ISSUE #1236: Update peerDependencies to angular 10
While using angular 10, yarn install produces following warning:
`warning " > ng2-charts@2.3.2" has incorrect peer dependency "@angular/common@^7.2.0 || ^8.0.0 || ^9.0.0".`

Current ng-charts version: 2.3.2

Do you have plans to update this dependency to version 10?

Thanks a lot.

### PR DESCRIPTION
**Pull request by EugeneLeclerc**
The package works well will Angular 10, so we just need to add the corresponding versions as  possible values in the peerDependencies in package.json.

### CODE REVIEW

**Comment by EugeneLeclerc** [comment]
Well there seems to be a problem with the CI :/

**Comment by inpercima** [comment]
@EugeneLeclerc Thanks for checking the issue and creating this PR. Hope the CI problem can be cleared.

**Comment by EugeneLeclerc** [comment]
Well I don't have the rights to fix the CI myself, so I just hope that @paviad will have the time to do it one day, or at least come and merge my PR. 

Anyway the fix is just for quality of life so it's no big deal.

**Comment by EugeneLeclerc** [comment]
This was resolved by https://github.com/valor-software/ng2-charts/commit/a9b15013dd3403af1c902822bf5e4b06b8e453a2.

**Pull request closed without merging**
