### PR TITLE
Angular 10 update

### PR DESCRIPTION
**Pull request by santam85**
Ran schematics, updated libraries to compatible versions and fixed compile issues.

### CODE REVIEW

**Comment by santam85** [comment]
@paviad any chance I could get access to Applitools? Demo app runs fine but visual tests keep failing...

**Comment by santam85** [comment]
@paviad Could you please have a look at this PR? I believe the Applitools diffs are caused by slight changes in the styling of Chart.js. I can't spot any inconsistencies and all charts seem to run fine in my tests!

**Comment by paviad** [comment]
I'll do my best to get around to it soon.

**Comment by paviad** [comment]
Hi I'm rebasing this on `development` also, do you recommend the version be bumped to 2.4.0? or should we keep it at 2.3.*?

**Comment by paviad** [comment]
Continue at pr #1245

**Comment by santam85** [comment]
According to semver best practices, we should probably bump to 3.0.0 due to the update to a new Angular major...

**Pull request closed without merging**
