### PR TITLE
Upgrade to Chart.js 3.0

### LINKED ISSUE #1214: chart Js 3.0 update
Hi

I was wondering if there are any plans to update ng2-charts to support the chart.js 3.0 release.

Thank you.

### PR DESCRIPTION
**Pull request by santam85**
Tested with latest Chart.js RC

fixes #1214

### CODE REVIEW

**Comment by santam85** [comment]
Tested successfully at the time of comment with the main branch versions of:
https://github.com/chartjs/chartjs-plugin-datalabels
https://github.com/chartjs/chartjs-plugin-annotation

Needs this PR (or a similar fix) to be merged:
https://github.com/chartjs/chartjs-plugin-annotation/pull/335

**Comment by santam85** [comment]
@paviad I think this is ready to be merged to development and released as an RC, would you take a look at it please?

**Review by valorkin — APPROVED** [review]
overall looks, good.
one question: was in necessary to make a breaking  change with renaming properties from datasets to data and from chartType to type?

**Comment by santam85** [comment]
> overall looks, good.
> one question: was in necessary to make a breaking change with renaming properties from datasets to data and from chartType to type?

The APIs to configure charts are changed slightly, and in the spirit to facilitate strong typing of configuration for the library I decided to change chartType to type, to match the typings and not having to maintain a separate set.

The datasets property was not renamed, it existed before as well. I changed some examples to use that instead for simplicity.

**Comment by valorkin** [comment]
@santam85 roger, sounds good to me

**Comment by santam85** [comment]
@valorkin do you think you could help with releasing this? @paviad does not seem to be very active on the project anymore!

**Comment by valorkin** [comment]
@santam85 drop me a note a valorkin@gmail.com let's arrange you an npm access

**Comment by santam85** [comment]
> @santam85 drop me a note a [valorkin@gmail.com](mailto:valorkin@gmail.com) let's arrange you an npm access

Sent you an email, thanks!

**Comment by michahell** [comment]
Thanks for doing this and picking this up @santam85! Any progress on getting this merged together with @valorkin or what are the current blockers?

**Comment by PowerKiKi** [comment]
It seems it is blocked by https://github.com/chartjs/chartjs-chart-financial/pull/95

**Comment by santam85** [comment]
Hello @michahell and @PowerKiKi, indeed the last outstanding dependency that needs to be migrated is fixed by https://github.com/chartjs/chartjs-chart-financial/pull/95
I updated both PRs today, hopefully @valorkin and the mantainers of the financial-chart library become more responsive and help me get this out the door.

**Comment by paviad** [comment]
@santam85 let me know exactly what needs to be done - I don't want to make a foul.

**Comment by santam85** [comment]
> @santam85 let me know exactly what needs to be done - I don't want to make a foul.

For starters, the CI seems to have stopped working, not sure what's going on there but it doesn't run on this PR.
I would like to merge this to the development branch, and start updating versions and docs there. When we are comfortable enough with the result, we can release it as a beta under the `next` label on NPM and start gathering feedback.

**Comment by paviad** [comment]
@santam85 if possible, join https://discord.gg/eAjRe2jNcT so we can have some real time chat please.

**Pull request merged**
