### PR TITLE
BREAKING drop hardcoded and generated colors

### PR DESCRIPTION
**Pull request by PowerKiKi**
`builtInDefaults` and `baseColors` were dropped. That means that colors 
will change to be the default as defined by Chart.js, and we will no 
longer generate colors on the fly.

If you need this kind of features, see https://www.chartjs.org/docs/latest/general/colors.html#advanced-color-palettes

As discussed in https://github.com/valor-software/ng2-charts/pull/1801#issuecomment-1916687084

To be merged afer https://github.com/valor-software/ng2-charts/pull/1804

### CODE REVIEW

**Comment by santam85** [comment]
Checks are failing because you only regenerated the macOS (darwin) screenshots. There is a command in the tools folder to regenerate the linux ones using Docker, but it might need some tweaking...

**Comment by PowerKiKi** [comment]
I'm on linux, so I am actually generating linux images:

image


However, I am having trouble to generate the correct screenshots systematically. They sometimes happens to be 1248px wide, whereas they should all be 600px. Could you give it a try on your side ?

**Comment by santam85** [comment]
Very strange this is happening to me too  now. Perhaps an update from Playwright could have caused it?

**Comment by santam85** [comment]
@PowerKiKi I ended up having to do substantial changes to the demo app, as it seems the e2e flakyness was caused by the canvas being hidden/animating while the chart was initializing in the lazy loaded tabs. See if the new setup works better for you too, I'll start working on fixing unit tests.

**Comment by PowerKiKi** [comment]
I rebased on top of master, and regenerated screenshots. It can now run consistently every single time on my machine. However I see the CI is  still failing... I'll see if I can grab the screen shot generated by CI...

**Comment by PowerKiKi** [comment]
I'm getting crazy here. I'm convinced that local e2e is non-flaky. I pushed to CI and it fails. I spend way too much time trying random things with constants failure. And when I'm about to give up, it works ! :roll_eyes: 

... so I guess it can be merged ... ?

**Review by santam85 — APPROVED** [review]

**Pull request merged**
