### PR TITLE
Add metadata.json file generation for Angular AoT compilation support

### PR DESCRIPTION
**Pull request by Tiedye**
Also in this is I updated angular and typescript so that the generation would work correctly

### CODE REVIEW

**Comment by Tiedye** [comment]
This pr does what #411 and #409 do, so if you merge this you need not merge wither of those

**Comment by otelnov** [comment]
npm run test please, tslint issues

**Comment by valorkin** [comment]
@Tiedye this is awesome! can you please fix tslint issues? Thanks in advance

**Comment by Tiedye** [comment]
Yeah Ill get right on that, thought I had them passed

**Comment by otelnov** [comment]
@Tiedye don't worry, I'm finishing merge

**Comment by otelnov** [comment]
fixed there https://github.com/valor-software/ng2-charts/pull/414
thanks

**Pull request closed without merging**
