### PR TITLE
fix(charts): Fix dynamic update of the chart labels

### LINKED ISSUE #614: Dynamically change generated labels not worked
Version: ng2-charts `v1.5.0`

Reproduction of the problem
http://plnkr.co/edit/Ggp7hasnGBsKTlq8hu1R?p=preview

Probably dynamically change generated labels feature was removed by this PR #563 .

related task to this feature #445

### PR DESCRIPTION
**Pull request by m0t0r**
Closes #614

### CODE REVIEW

**Comment by m0t0r** [comment]
@valorkin could you please merge this PR ?

**Comment by m0t0r** [comment]
Hi @valorkin, or anyone from @valor-software can you please review this PR ?

**Comment by valorkin** [comment]
Next week I will be merging reviewing PRs, and pushing to ngx- namespace

**Comment by ronaldgrn** [comment]
Any updates on this?

**Comment by nomah82** [comment]
it seems that no :(

**Pull request closed without merging**
