### PR TITLE
Angular 17

### PR DESCRIPTION
**Pull request by santam85**
Upgrade build to Angular 17

### CODE REVIEW

**Comment by PowerKiKi** [comment]
@santam85 the build failed. It seems the screenshots changed a bit. Are you able to fix that ?

@valorkin, assuming the CI passes, would you have any other feedback before merging this ?

**Comment by santam85** [comment]
I'll push the new screenshots when I have a minute (requires some time as it has to run in a docker container and having trouble with that). There are a few more issues I'd like to address with the unit tests for the doc site, but that doesn't block releasing of an Angular 17 version of the lib. Would be nice if someone could contribute the modernization part, IE: switching to signals, module-less etc., so that it's not only a bump in the peer dependencies.

**Comment by PowerKiKi** [comment]
I am interested in standalone, so I'd create a PR for it. But it seems better to wait for this one to be merged, because it it contains quite a few changes that I'd rather already have when working on my PR.

**Comment by santam85** [comment]
@PowerKiKi PR is merged, but I will wait to release until some work is done to modernize the lib for 17 and fix the unit testing issues, thanks for having a look at that! 🙏

**Comment by PowerKiKi** [comment]
Thanks for the heads up. I had a quick look but `npm run start` will fail with errors similar to the following. Since this was introduced in this PR, maybe there is something I should know ? Does this code require node 20 (I am on 18) ?


```
✘ [ERROR] Could not resolve "../bar-chart/bar-chart.component.txt"

    apps/ng2-charts-demo/src/app/chart-host/chart-host.component.ts:3:18:
      3 │ import barTs from '../bar-chart/bar-chart.component.txt';
        ╵                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by santam85** [comment]
there is a `prebuild:prod` script you can run to generate those

**Pull request merged**
