### PR TITLE
Add support for changing graph labels

### PR DESCRIPTION
**Pull request by cthielen**
ng2-charts currently supports changing data but not graph labels.

Our application has a date filter which removes or adds data points entirely, requiring the graph labels themselves to update with the data.

This simple fix allows the labels to change as well when detected by ngOnChanges.

### CODE REVIEW

**Comment by antoinegiret** [comment]
Hello, is it possible to merge it? :)

**Comment by ADringer** [comment]
Is there any update on this? This is exactly the update I need for the project. Is ng2-charts still supported?

**Comment by byrondover** [comment]
@valorkin Please advise.

**Comment by valorkin** [comment]
In one or 2 weeks I will be able to assign dev and qa to merge and release existing PRs, then upgrade to ngv4+ and rename to ngx

**Comment by carvarr** [comment]
guys, any update on this ?

**Pull request closed without merging**
